# Environment Setup

## Imports

In [25]:
import numpy as np
import matplotlib as plt
import copy
from pprint import pprint
import random
import operator

## Setting up State Space

In [3]:
state_space = np.zeros((5, 10))
for i in range(0, len(state_space)-1):
    for j in range(0, len(state_space[i]-1)):
        state_space[i][j] = -1
for i in range(0, len(state_space[-1])):
    if 0 < i and i < len(state_space[-1])-1:
        state_space[-1][i] = -100
    elif i == len(state_space[-1])-1:
        state_space[-1][i] = 20
print(state_space)

[[  -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.]
 [  -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.]
 [  -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.]
 [  -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.]
 [   0. -100. -100. -100. -100. -100. -100. -100. -100.   20.]]


## Define possible actions for each state

In [15]:
possible_actions = {}
for i in range(0, len(state_space)):
    for j in range(0, len(state_space[i])):
        list_of_actions = []
        # Each state has a maximum of 4 possible actions (New states to transition to)
        # We check the boundaries to ensure we do not add an action outside our state space
        if not (i-1 < 0):
            list_of_actions.append((i-1, j))
        if not (i+1 >= len(state_space)):
            list_of_actions.append((i+1, j))
        if not (j-1 < 0):
            list_of_actions.append((i, j-1))
        if not(j+1 >= len(state_space[i])):
            list_of_actions.append((i, j+1))
        possible_actions[(i, j)]= list_of_actions

## $\epsilon$-greedy Policy

In [52]:
# input: State Space, current state, List of possible actions (locations), epsilon value
# returns: new action (location tuple)
def policy(state_space: list, possible_actions: dict, current_state: tuple, e: float = 0.1) -> tuple:
    action_payoffs = {}
    # retreiving payoffs of possible actions
    for action in possible_actions[current_state]:
        i, j = action
        action_payoffs[action] = state_space[i][j]
    # Decide with the e-greedy policy the action to return
    if random.random() > e:
        return max(action_payoffs, key=action_payoffs.get)
    return random.choice(list(action_payoffs.keys()))
a, b = policy(state_space, possible_actions, (4, 0))
print (a, b)

3 0


# SARSA

In [ ]:
def SARSA(alpha: float = 1, gamma: float = 1) -> any:
    pass

# Q-Learning

In [ ]:
def Q_Learning() -> any:
    pass

# Tests

In [ ]:
def tests() -> None:
    pass